version: "3.6"

volumes:
  web_build:
  api_build:
  api_node_modules:
  web_node_modules:
  db_data:
  redis_data:
  organizr_config:

networks:
  default:

services:
  bobarr-1080-api:
    container_name: bobarr-1080-api
    env_file: .env
    environment:
      - WEB_UI_API_URL=http://api-1080:4000
      - API_QUALITY=1080
      - POSTGRES_DB=bobarr1080
      - PORT=4000
    image: longlivethepenguin/bobarr-1080-api:latest
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - ./library:/usr/library
    ports:
      - 4000:4000

  bobarr-720-api:
    container_name: bobarr-1080-api
    env_file: .env
    environment:
      - WEB_UI_API_URL=http://api-720:4001
      - API_QUALITY=720
      - POSTGRES_DB=bobarr720
      - PORT=4001
    image: longlivethepenguin/bobarr-720-api:latest
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - ./library:/usr/library
    ports:
      - 4001:4001

  bobarr-1080-web:
    container_name: bobarr-web
    env_file: .env
    environment:
      - WEB_UI_API_URL=http://api-1080:4000
      - API_QUALITY=1080
      - PORT=3000
    image: longlivethepenguin/bobarr-1080-web:latest
    command: yarn start
    restart: unless-stopped
    ports:
      - 3000:3000

  bobarr-720-web:
    container_name: bobarr-web
    env_file: .env
    environment:
      - WEB_UI_API_URL=http://api-720:4001
      - API_QUALITY=720
      - PORT=3001
    image: longlivethepenguin/bobarr-720-web:latest
    command: yarn start
    restart: unless-stopped
    ports:
      - 3001:3001

  postgres:
    container_name: bobarr-postgresql
    image: postgres:12-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: bobarr-redis
    image: bitnami/redis:5.0.6
    env_file: .env
    restart: unless-stopped
    volumes:
      - redis_data:/bitnami/redis/data
      - ./packages/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf

  jackett:
    image: linuxserver/jackett
    container_name: bobarr-jacket
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./packages/jackett/config:/config
      - ./packages/jackett/downloads:/downloads
    ports:
      - 9117:9117

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: bobarr-flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    ports:
      - 8191:8191

  transmission:
    image: linuxserver/transmission
    container_name: bobarr-transmission
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./library/downloads:/downloads
      - ./packages/transmission/config:/config
      - ./packages/transmission/watch:/watch

  transmission-web:
    image: dperson/nginx
    container_name: bobarr-transmission-web
    depends_on:
      - transmission
    env_file: .env
    ports:
      - "9091:80"
    command: -w "http://transmission:9091;/"
    restart: unless-stopped

  organizr:
    container_name: organizr
    image: organizr/organizr
    env_file: .env
    environment:
      - fpm="false" #optional
    volumes:
      - organizr_config:/config
    ports:
      - 80:80
    restart: unless-stopped
