version: "3.6"

volumes:
  api_1080_node_modules:
  api_1080_build:
  api_720_node_modules:
  api_720_build:
  web_1080_node_modules:
  web_1080_build:
  web_720_node_modules:
  web_720_build:

services:
  api_1080:
    build:
      context: ./packages/api-1080
    command: yarn dev
    volumes:
      - ./packages/api-1080:/usr/src/app
      - api_1080_node_modules:/usr/src/app/node_modules
      - api_1080_build:/usr/src/app/dist
    
  web_1080:
    build:
      context: ./packages/web-1080
    command: yarn dev
    environment:
      - WEB_UI_API_URL=http://127.0.0.1:4000
    volumes:
      - ./packages/web-1080:/usr/src/app
      - web_1080_node_modules:/usr/src/app/node_modules
      - web_1080_build:/usr/src/app/.next
    
  api_720:
    build:
      context: ./packages/api-720
    command: yarn dev
    volumes:
      - ./packages/api-720:/usr/src/app
      - api_720_node_modules:/usr/src/app/node_modules
      - api_720_build:/usr/src/app/dist

  web_720:
    build:
      context: ./packages/web-720
    command: yarn dev
    environment:
      - WEB_UI_API_URL=http://127.0.0.1:4001
    volumes:
      - ./packages/web-720:/usr/src/app
      - web_720_node_modules:/usr/src/app/node_modules
      - web_720_build:/usr/src/app/.next

  # postgres:
  #   ports:
  #     - 5432:5432

  # redis:
  #   ports:
  #     - 6379:6379
