version: "3.6"

volumes:
  api_1080_node_modules:
  api_1080_build:
  api_720_node_modules:
  api_720_build:
  web_1080_node_modules:
  web_1080_build:
  web_720_node_modules:
  web_720_build:

services:
  api_1080:
    build:
      context: ./packages/api
    command: yarn dev
    volumes:
      - ./packages/api:/usr/src/app
      - api_1080_node_modules:/usr/src/app/node_modules
      - api_1080_build:/usr/src/app/dist
    environment:
      - PORT=4000

  web_1080:
    build:
      context: ./packages/web
    command: yarn dev
    volumes:
      - ./packages/web:/usr/src/app
      - web_1080_node_modules:/usr/src/app/node_modules
      - web_1080_build:/usr/src/app/.next
    environment:
      - PORT=3000

  api_720:
    build:
      context: ./packages/api
    command: yarn dev
    volumes:
      - ./packages/api:/usr/src/app
      - api_720_node_modules:/usr/src/app/node_modules
      - api_720_build:/usr/src/app/dist
    environment:
      - PORT=4001

  web_720:
    build:
      context: ./packages/web
    command: yarn dev
    volumes:
      - ./packages/web:/usr/src/app
      - web_720_node_modules:/usr/src/app/node_modules
      - web_720_build:/usr/src/app/.next
    environment:
      - PORT=3001

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
